### ISSUE TITLE
Update the links in the footer section to point to MC URLs.

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/mcta#4]
As per slack conversation dated 11/30/2017 update links to:
•Documentation: https://sites.google.com/mercycorps.org/tolauserguide/home
•Feedback: https://goo.gl/forms/VuG2UjlBeTAGdJ503
•FAQ: https://thehub.mercycorps.org/page/7271

**Comment by jennyhavah** [comment]
@mahmoodkhan Did you see my comment in Slack about not being able to access the Form Guidance page from Indicators? Not sure if that is connected with this issue or if we should file a separate one?
